#!/bin/sh

#
# jupyter tool
#
/usr/bin/invoke_app "$@" -t icesheet1 \
                         -C "start_jupyter -A -T @tool -t icesheet1.ipynb" \
                         -u anaconda-7 \
                         -r none \
                         -w headless
